alter policy album_entries_read_own     on public.album_entries            using (user_id = (select auth.uid()));
alter policy alpha_welcome_read_own      on public.alpha_welcome            using (user_id = (select auth.uid()));
alter policy cardattr_select_own         on public.card_instance_attributes using (exists (select 1 from card_instances ci where ci.id = card_instance_attributes.card_instance_id and ci.owner_id = (select auth.uid())));
alter policy card_select_own             on public.card_instances           using ((select auth.uid()) = owner_id);
alter policy ledger_select_own           on public.currency_ledger          using ((select auth.uid()) = user_id);
alter policy data_requests_read_own      on public.data_requests            using (user_id = (select auth.uid()));
alter policy feedback_read_own           on public.feedback                 using (user_id = (select auth.uid()));
alter policy legal_acceptance_read_own   on public.legal_acceptance         using (user_id = (select auth.uid()));
alter policy packopen_select_own         on public.pack_openings            using ((select auth.uid()) = user_id);
alter policy player_avatars_read         on public.player_avatars           using (user_id = (select auth.uid()));
alter policy player_cosmetics_read       on public.player_cosmetics         using ((select auth.uid()) = user_id);
alter policy prof_select_own             on public.profiles                 using ((select auth.uid()) = id);
alter policy qsessans_select_own         on public.quiz_session_answers     using (exists (select 1 from quiz_sessions s where s.id = quiz_session_answers.session_id and s.user_id = (select auth.uid())));
alter policy qsess_select_own            on public.quiz_sessions            using ((select auth.uid()) = user_id);
alter policy ranked_teams_own            on public.ranked_teams             using (player_id = (select auth.uid()));
alter policy tradeitem_select_parties    on public.trade_offer_items        using (exists (select 1 from trade_offers t where t.id = trade_offer_items.trade_offer_id and (t.from_user_id = (select auth.uid()) or t.to_user_id = (select auth.uid()))));
alter policy trade_select_parties        on public.trade_offers             using ((select auth.uid()) = from_user_id or (select auth.uid()) = to_user_id);
alter policy userach_select_own          on public.user_achievements        using ((select auth.uid()) = user_id);;
